apiVersion: apps/v1
kind: ReplicaSet
metadata: 
  name: helloword-controller
  labels:
    app: helloworld
spec:
  replicas: 5
  selector:
    matchLabels:
      app: helloworld
  template:
     metadata:
       labels:
         app: helloworld
     spec:
       containers:
       - name: my-python-image
         image: arjunachari12/my-python-image
         ports:
           containerPort: 3000
